ERROR - 2022-06-23 12:48:57 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-23 12:48:57 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(`c...', Array, false)
#2 C:\xampp\htdocs\contactapp_ci4\app\Models\M_client.php(30): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Home.php(22): App\Models\M_client->tabel()
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->grafik()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-06-23 12:49:02 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-23 12:49:02 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(21): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->read()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-06-23 12:49:53 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-23 12:49:53 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(21): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->read()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-06-23 12:50:44 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-23 12:50:44 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(21): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->read()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-23 13:27:56 --> require is not a valid rule.
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('nama_update', 'nama_update', 'erikaa', Array, Array)
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(72): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->update()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-23 13:31:12 --> require is not a valid rule.
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('nama_update', 'nama_update', 'erika', Array, Array)
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(72): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->update()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-23 13:35:02 --> require is not a valid rule.
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('require')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('nama_update', 'nama_update', 'erika', Array, Array)
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Controller.php(183): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Contact.php(72): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\contact->update()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\contact))
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-06-23 19:42:13 --> Table 'contact_di4.client' doesn't exist
CRITICAL - 2022-06-23 19:42:13 --> Table 'contact_di4.client' doesn't exist
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT COUNT(`c...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(`c...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(`c...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(`c...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\app\Models\M_client.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Home.php(22): App\Models\M_client->tabel()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->grafik()
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-06-23 19:46:12 --> Header may not contain more than a single header, new line detected
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Header may not ...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\contactapp_ci4\app\Views\akun\tabel.php(165): header('Contact-type: a...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('/akun/tabel', Array, true)
#5 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Akun.php(17): view('/akun/tabel')
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Akun->index()
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Akun))
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-06-23 20:42:27 --> Undefined property: App\Controllers\login::$m_user
#0 C:\xampp\htdocs\contactapp_ci4\app\Controllers\login.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->auth()
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-23 20:42:34 --> Undefined property: App\Controllers\login::$m_user
#0 C:\xampp\htdocs\contactapp_ci4\app\Controllers\login.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\login->auth()
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2022-06-23 20:43:31 --> Table 'contact_di4.client' doesn't exist
CRITICAL - 2022-06-23 20:43:31 --> Table 'contact_di4.client' doesn't exist
#0 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('SELECT COUNT(`c...')
#1 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(`c...')
#2 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(`c...')
#3 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(`c...', Array, false)
#4 C:\xampp\htdocs\contactapp_ci4\app\Models\M_client.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\contactapp_ci4\app\Controllers\Home.php(22): App\Models\M_client->tabel()
#6 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Home->grafik()
#7 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\contactapp_ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\contactapp_ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
